services:
  - type: web
    name: fb-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_CSV_URL
        sync: false
      - key: DOMAIN
        value: fb-gpt-chatbot.onrender.com
      - key: FANPAGE_NAME
        value: "Shop th·ªùi trang"
      - key: FCHAT_WEBHOOK_URL
        sync: false
      - key: FCHAT_TOKEN
        sync: false
